lints.workspace = true

[package]
name = "gix-note"
version = "0.0.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing with git notes"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2024"
rust-version = "1.85"
include = ["/src/**/*", "/LICENSE-*"]

[lib]
doctest = false

[features]
## Enable support for the SHA-1 hash by forwarding it to dependencies.
sha1 = ["gix-hash/sha1", "gix-object/sha1"]
## Enable support for the SHA-256 hash by forwarding it to dependencies.
sha256 = ["gix-hash/sha256", "gix-object/sha256"]

[dependencies]
gix-error = { version = "^0.2.5", path = "../gix-error" }
gix-hash = { version = "^0.26.0", path = "../gix-hash" }
gix-object = { version = "^0.63.0", path = "../gix-object" }

[dev-dependencies]
gix-note = { path = ".", features = ["sha1", "sha256"] }
gix-odb = { path = "../gix-odb" }
gix-testtools = { path = "../tests/tools" }
