lints.workspace = true

[package]
name = "gix-fs"
version = "0.22.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate providing file system specific utilities to `gitoxide`"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2024"
rust-version = "1.85"
include = ["/src/**/*", "/LICENSE-*"]

[lib]
doctest = true

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde"]

[dependencies]
bstr = "1.12.0"
gix-path = { version = "^0.12.4", path = "../gix-path" }
gix-features = { version = "^0.49.0", path = "../gix-features", features = ["fs-read-dir"] }
gix-utils = { version = "^0.3.5", path = "../gix-utils" }
gix-error = { version = "^0.2.5", path = "../gix-error" }
serde = { version = "1.0.114", optional = true, default-features = false, features = ["std", "derive"] }

[dev-dependencies]
crossbeam-channel = "0.5.15"
is_ci = "1.1.1"
tempfile = "3.26.0"
